apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shadownet-ingress
  namespace: shadownet
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/websocket-services: "shadownet-api"
spec:
  ingressClassName: nginx
  rules:
    - host: shadownet.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shadownet-api
                port:
                  number: 8000
